Only start daemon if not using host services

diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -52,10 +52,14 @@ startup()
         systemctl is-active otbr-agent || sudo systemctl start otbr-agent || die 'Failed to start otbr-agent!'
     elif have service; then
         sudo service rsyslog status || sudo service rsyslog start || die 'Failed to start rsyslog!'
-        sudo service dbus status || sudo service dbus start || die 'Failed to start dbus!'
-        # Tolerate the mdns failure as it is installed for only CI docker.
-        sudo service mdns status || sudo service mdns start || echo "service mdns is not available!"
-        sudo service avahi-daemon status || sudo service avahi-daemon start || die 'Failed to start avahi!'
+        if [ ! -e "/run/dbus" ]; then
+            sudo service dbus status || sudo service dbus start || die 'Failed to start dbus!'
+        fi
+        if [ ! -e "/run/avahi-daemon/socket" ]; then
+            # Tolerate the mdns failure as it is installed for only CI docker.
+            sudo service mdns status || sudo service mdns start || echo "service mdns is not available!"
+            sudo service avahi-daemon status || sudo service avahi-daemon start || die 'Failed to start avahi!'
+        fi
         sudo service otbr-agent status || sudo service otbr-agent start || die 'Failed to start otbr-agent!'
         without WEB_GUI || sudo service otbr-web status || sudo service otbr-web start || die 'Failed to start otbr-web!'
     else
